version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projeto_aws
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: node_app
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/projeto_aws?schema=public"
      JWT_SECRET: "sua_chave_secreta_aqui"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres_data:

networks:
  app-network:
